name: fit_help_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  flashy_tab_bar2: ^0.0.6
  flutter:
    sdk: flutter
  flutter_html: ^2.1.2
  flutter_profile_picture: ^2.0.0
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  http: ^0.13.6
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
